AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

# Allow both styles for arrays
Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Disable development dependencies warning (they're fine in gemspec)
Gemspec/DevelopmentDependencies:
  Enabled: false
