# Rails internal tables that should always be excluded
- schema_migrations
- ar_internal_metadata
- active_storage_blobs
- active_storage_attachments
- active_storage_variant_records
- action_text_rich_texts
- action_mailbox_inbound_emails
- action_mailbox_entries
- solid_queue_blocked_executions
- solid_queue_claimed_executions
- solid_queue_failed_executions
- solid_queue_jobs
- solid_queue_pauses
- solid_queue_processes
- solid_queue_ready_executions
- solid_queue_recurring_executions
- solid_queue_scheduled_executions
- solid_queue_semaphores